version: '3.5'

services:
  database-postgres:
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - my-portfolio-network-api
    restart: on-failure
    tty: true
networks:
  my-portfolio-network-api:
    name: my-portfolio-network-api