version: '3.5'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: "America/Sao_Paulo"
    networks:
      - my-portfolio-network-api
    restart: always

networks:
  my-portfolio-network-api:
    driver: bridge
    name: my-portfolio-network-api
